version: '3'
services:
  # Spring Boot application
  spring-app:
    image: your-spring-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/book
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Iwork@ctli8
    depends_on:
      - mysql-db

  # MySQL database
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Iworkctli8
      MYSQL_DATABASE: book
      MYSQL_USER: root
      MYSQL_PASSWORD: Iwork@ctli8